apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
type: Opaque
data:
  rabbitmq-user: {{ .Values.secrets.rabbitmqUser | b64enc }}
  rabbitmq-pass: {{ .Values.secrets.rabbitmqPass | b64enc }}
  redis-password: {{ .Values.secrets.redisPassword | b64enc }}
